ALTER TABLE system_settings
    ADD COLUMN IF NOT EXISTS notice_message VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS notice_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS maintenance_mode BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS signup_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS ai_report_enabled BOOLEAN NOT NULL DEFAULT TRUE;
